server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1

management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info"
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

