server:
  port: 0

spring:
  application:
    name: order
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/smarthome"
    username: "postgres"
    password: "12345"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: order
        format_sql: true