# Kafka Configuration
kafka.bootstrap-servers=localhost:9092
kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

kafka.topics.snapshots=telemetry.snapshots.v1
kafka.topics.hubs=telemetry.hubs.v1

kafka.hub-consumer-properties.group-id=analyzer-hub-group
kafka.hub-consumer-properties.value-deserializer=ru.yandex.practicum.deserializer.HubEventDeserializer

kafka.snapshot-consumer-properties.group-id=analyzer-snapshot-group
kafka.snapshot-consumer-properties.value-deserializer=ru.yandex.practicum.deserializer.SensorsSnapshotDeserializer

# gRPC Client
grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

# Database Configuration
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Schema initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql