# Kafka topics
kafka:
  topic:
    hub: telemetry.hubs.v1
    sensor: telemetry.sensors.v1
  bootstrap:
    server: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Server ports
server:
  port: 8080

# gRPC configuration
grpc:
  server:
    port: 59091